### ISSUE TITLE
Header not found error on new project

### ISSUE THREAD

**Issue by adennen** [netguru/devise-ios#2]
Hello, I've been having trouble getting a simple project to compile after I add #import <Devise/Devise.> to AppDelegate.h.

Steps to replicate:
* Create a new single view iOS application
* Create a podfile in the root of the application with the contents:
```ruby
platform :ios, '7.0'

# Pod sources
pod 'Devise', '~> 0.1.1'
```
* Run 'pod install'
* In AppDelegate.h, add the following line under import UIKit.h:
```obj-c
#import <Devise/Devise.h> 
```
* Build the project

error message appears:
~/Developer/deleteDevise2/Pods/Headers/Public/Devise/Devise.h:14:13: 'Devise/DVSHTTPClient.h' file not found

**Comment by WojciechTrzasko** [comment]
Hi @adennen

First of all thanks for your support :) We really appreciate it :smile:.

But lets go back to our problem with imports. After some investigation it turned out that verision 0.1.1 was pointing to commit with bug that was affecting path to public headers in our podspec. The new version 0.1.2 contains fix for this issue. To resolve your problems please use `pod install` to update pod to newest version.

Thanks for your patience and please let us know if it you still have problems with our library.
