### ISSUE TITLE
RestKit compatibility?

### ISSUE THREAD

**Issue by imton** [netguru/devise-ios#7]
Guys! 

This is awesome. Sadly I see you are using AFNetworking >= 2 which prevent's using RestKit, because it still uses <= 1 :( 

Any workaround? 

Thanks!

**Comment by PatrykKaczmarek** [comment]
Hey @imton 

We investigated your request and decided to drop AFNetworking dependency. Provided changes do not affect any of devise-ios features. Since now you can use:
```
pod 'Devise',
    :git => "git@github.com:netguru/devise-ios.git",
    :branch => "feature/restkit-compatibility"
```
Please notice that this is `feature` branch. If some exceptions and/or not working features will appear please don't hesitate to tell us about discovered issue.

**Comment by imton** [comment]
Hi guys! Thank you for this. Sadly I had to use other options this weekend but will definitely give it a try for other projects later.

**Comment by PatrykKaczmarek** [comment]
FYI: From version `1.1.0` Devise is fully compatible with RestKit.
